---
- name: Installation RHSCL nightly builds
  hosts: all


- tasks:
    - name: Install import packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - curl
        - jq
        - cronie
        - postfix
        - mailx

    - name: Add relay host
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: '^relayhost = '

    - name: Start and enable crond service
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - crond
        - postfix

    - name: Copy a warning script that the machine is managed by ansible
      copy:
        src: "files/warning.sh"
        dest: "/home/fedora/warning.sh"

    - name: Add warning text instead of installe
      lineinfile:
        path: /home/fedora/.bashrc
        line: 'source warning.sh'
        state: present

# Schedule NightlyBuild at 1 am each day
# * 1 * * 1-5 /home/fedora/ci-scripts/run_nightly_tests.sh rhel7 test
# * 1 * * 1-5 /home/fedora/ci-scripts/run_nightly_tests.sh rhel8 test
# * 1 * * 1-5 /home/fedora/ci-scripts/run_nightly_tests.sh centos7 test
# * 1 * * 1-5 /home/fedora/ci-scripts/run_nightly_tests.sh fedora test
